export const RULE_DATA_VERSION = 'claudify-v2-2026-09-01';

const archaicPhraseRules = Object.freeze([
  { id: 'lex-archaic-tis', triggers: ['’Tis'], variants: ['It is'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-tis-nobler', triggers: ['’Tis nobler in the mind'], variants: ["It’s more strategically admirable"], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-to-suffer', triggers: ['To suffer'], variants: ['To endure / absorb the downside'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-slings-arrows', triggers: ['The slings and arrows'], variants: ['The attacks and setbacks'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-outrageous-fortune', triggers: ['Outrageous fortune'], variants: ['Extreme bad luck / a hostile external environment'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-take-arms', triggers: ['To take arms'], variants: ['To take action / mobilize'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-sea-troubles', triggers: ['A sea of troubles'], variants: ['An overwhelming volume of problems'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-opposing-end', triggers: ['By opposing end them'], variants: ['By actively pushing back, eliminate them'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-die-sleep', triggers: ['To die—to sleep'], variants: ['To die is essentially to shut down'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-no-more', triggers: ['No more'], variants: ['No further pain or disruption'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-by-sleep', triggers: ['By a sleep'], variants: ['Through death / permanent shutdown'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-heartache', triggers: ['The heartache'], variants: ['Emotional pain'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-thousand-shocks', triggers: ['The thousand natural shocks'], variants: ['The countless unavoidable difficulties'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-flesh-heir', triggers: ['That flesh is heir to'], variants: ['That human beings inevitably experience'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-consummation', triggers: ['A consummation'], variants: ['A final resolution / complete wrap-up'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-devoutly-wished', triggers: ['Devoutly to be wished'], variants: ['Strongly desirable'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-perchance', triggers: ['Perchance'], variants: ['Perhaps / potentially'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-ay', triggers: ['Ay'], variants: ['Yes / indeed'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-rub', triggers: ['There’s the rub'], variants: ['That’s the key issue'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-sleep-death', triggers: ['The sleep of death'], variants: ['The unknown state after death'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-dreams-come', triggers: ['What dreams may come'], variants: ['Whatever may happen afterward'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-shuffled-off', triggers: ['Shuffled off'], variants: ['Discarded / exited'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-mortal-coil', triggers: ['This mortal coil'], variants: ['This difficult human existence'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-give-pause', triggers: ['Must give us pause'], variants: ['Should make us stop and reconsider'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-respect', triggers: ['There’s the respect'], variants: ['That’s the factor we have to account for'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-calamity-life', triggers: ['Makes calamity of so long life'], variants: ['Turns life’s problems into a reason to keep enduring them'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-who-would-bear', triggers: ['Who would bear'], variants: ['Who would willingly tolerate'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-whips-scorns', triggers: ['The whips and scorns of time'], variants: ['The constant criticism, pressure, and setbacks of life'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-oppressors-wrong', triggers: ["Th’ oppressor’s wrong"], variants: ['The abuse inflicted by powerful people'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-proud-contumely', triggers: ["The proud man’s contumely"], variants: ['The arrogance and insults of entitled people'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-pangs-love', triggers: ['The pangs of despised love'], variants: ['The pain of rejected or unreturned love'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-laws-delay', triggers: ['The law’s delay'], variants: ['Slow, inefficient legal processes'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-insolence-office', triggers: ['The insolence of office'], variants: ['The arrogance and abuse of people in positions of authority'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-spurns', triggers: ['The spurns'], variants: ['The rejections and humiliations'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-patient-merit', triggers: ['Patient merit'], variants: ['Quietly earned success / deserving people’s hard work'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-unworthy', triggers: ['Th’ unworthy'], variants: ['People who are less deserving'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-quietus', triggers: ['His quietus make'], variants: ['End his account / shut down his existence'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-bodkin', triggers: ['A bare bodkin'], variants: ['A simple dagger / one decisive action'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-fardels', triggers: ['Fardels'], variants: ['Burdens / difficult responsibilities'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-grunt-sweat', triggers: ['To grunt and sweat'], variants: ['To struggle and work painfully hard'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-weary-life', triggers: ['Under a weary life'], variants: ['Through an exhausting existence'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-dread', triggers: ['The dread'], variants: ['The fear'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-after-death', triggers: ['Something after death'], variants: ['The possibility of what comes next'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-undiscovered-country', triggers: ['The undiscovered country'], variants: ['An unknown future destination'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-bourn', triggers: ['From whose bourn'], variants: ['From whose boundary or territory'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-no-traveller', triggers: ['No traveller returns'], variants: ['No one comes back with verified information'], category: 'lexicalCliche', priority: 40 }
]);

const additionalArchaicPhraseRules = Object.freeze([
  { id: 'lex-archaic-thou', triggers: ['Thou'], variants: ['You'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-dost', triggers: ['Dost'], variants: ['Do'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-plague', triggers: ['Plague'], variants: ['Systemic downside vector'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-dowry', triggers: ['Dowry'], variants: ['Marriage-related asset package'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-calumny', triggers: ['Calumny'], variants: ['Damaging public criticism'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-if-thou-dost-marry', triggers: ['If thou dost marry'], variants: ['If you decide to get married'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-get-thee-nunnery', triggers: ['Get thee to a nunnery'], variants: ['Remove yourself from the relationship ecosystem'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-thee', triggers: ['Thee'], variants: ['You'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-wilt', triggers: ['Wilt'], variants: ['Will'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-if-thou-wilt-needs-marry', triggers: ['If thou wilt needs marry'], variants: ['If you insist on getting married'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-marry-fool', triggers: ['Marry a fool'], variants: ['Choose a less perceptive partner'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-wise-men-know', triggers: ['Wise men know well enough'], variants: ['Intelligent people understand the risks involved'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-go-farewell', triggers: ['Go, farewell'], variants: ['Leave now; this conversation is over'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-hath', triggers: ['Hath'], variants: ['Has'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-god-hath-given', triggers: ['God hath given you one face'], variants: ['You were given an authentic identity'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-make-yourselves-another', triggers: ['You make yourselves another'], variants: ['You replace it with a manufactured public persona'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-wantonness-ignorance', triggers: ['Make your wantonness your ignorance'], variants: ['Use deliberate foolishness to disguise irresponsible behavior'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-go-to', triggers: ['Go to'], variants: ['Come on / enough of this'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-ont', triggers: ['On’t'], variants: ['Of it'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-no-more-ont', triggers: ['I’ll no more on’t'], variants: ['I’m done discussing it'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-made-me-mad', triggers: ['It hath made me mad'], variants: ['The situation has pushed me past my limit'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-conscience', triggers: ['Conscience'], variants: ['Self-awareness / internal ethical review'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-resolution', triggers: ['Resolution'], variants: ['Determination / willingness to act'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-enterprises', triggers: ['Enterprises'], variants: ['Major initiatives / projects'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-moment', triggers: ['Moment'], variants: ['Significance / impact'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-puzzles', triggers: ['Puzzles'], variants: ['Confuses / creates uncertainty about'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-ills', triggers: ['Ills'], variants: ['Problems / negative conditions'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-bear-ills', triggers: ['Bear those ills we have'], variants: ['Continue tolerating our existing problems'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-fly-others', triggers: ['Fly to others'], variants: ['Escape toward alternative options'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-know-not-of', triggers: ['That we know not of'], variants: ['Whose consequences we cannot predict'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-makes-cowards', triggers: ['Makes cowards of us all'], variants: ['Causes universal hesitation and risk aversion'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-native-hue', triggers: ['Native hue'], variants: ['Natural appearance / original energy'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-sicklied-oer', triggers: ['Sicklied o’er'], variants: ['Made pale, weak, or ineffective'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-oer', triggers: ['O’er'], variants: ['Over'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-pith', triggers: ['Pith'], variants: ['Substance / strategic importance'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-with-this-regard', triggers: ['With this regard'], variants: ['Because of this concern'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-turn-awry', triggers: ['Turn awry'], variants: ['Go off course'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-lose-name-action', triggers: ['Lose the name of action'], variants: ['Stop producing meaningful results'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-soft-you-now', triggers: ['Soft you now'], variants: ['Wait a moment / pause the discussion'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-nymph', triggers: ['Nymph'], variants: ['Young woman, poetically idealized'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-thy', triggers: ['Thy'], variants: ['Your'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-orisons', triggers: ['Orisons'], variants: ['Prayers / personal reflections'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-remembered', triggers: ['Rememb’red'], variants: ['Remembered'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-how-now', triggers: ['How now?'], variants: ['What’s happening? / What’s the situation?'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-my-lord', triggers: ['My lord'], variants: ['My superior / sir'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-as-you-please', triggers: ['As you please'], variants: ['According to your preference'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-hold-it-fit', triggers: ['Hold it fit'], variants: ['Consider it appropriate'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-origin', triggers: ['Origin'], variants: ['Root cause'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-commencement', triggers: ['Commencement'], variants: ['Beginning / initial trigger'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-grief', triggers: ['Grief'], variants: ['Emotional distress'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-sprung-from', triggers: ['Sprung from'], variants: ['Resulted from'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-neglected-love', triggers: ['Neglected love'], variants: ['Unreciprocated or ignored romantic interest'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-queen-mother', triggers: ['Queen mother'], variants: ['The king’s mother, who is also queen'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-entreat-him', triggers: ['Entreat him'], variants: ['Ask or urge him earnestly'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-round-with-him', triggers: ['Round with him'], variants: ['Speak to him directly and frankly'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-placed', triggers: ['Plac’d'], variants: ['Positioned / assigned'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-in-the-ear-of', triggers: ['In the ear of'], variants: ['Present to overhear / included in'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-find-him-not', triggers: ['Find him not'], variants: ['Fail to identify or resolve the problem'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-send-england', triggers: ['Send him to England'], variants: ['Transfer him out of the current environment'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-where-wisdom', triggers: ['Where your wisdom best shall think'], variants: ['Wherever you judge most strategically appropriate'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-chuck', triggers: ['Chuck'], variants: ['Dear one / affectionate nickname'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-innocent-knowledge', triggers: ['Be innocent of the knowledge'], variants: ['Remain unaware of the plan'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-till-applaud-deed', triggers: ['Till thou applaud the deed'], variants: ['Until you approve the completed action'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-seeling', triggers: ['Seeling'], variants: ['Closing or blinding'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-seeling-night', triggers: ['Seeling night'], variants: ['Night that blocks visibility'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-scarf-up', triggers: ['Scarf up'], variants: ['Cover / conceal'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-tender-eye', triggers: ['Tender eye'], variants: ['Delicate, vulnerable light'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-pitiful-day', triggers: ['Pitiful day'], variants: ['Gentle daylight'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-bloody-invisible-hand', triggers: ['Bloody and invisible hand'], variants: ['Secret, violent intervention'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-keeps-pale', triggers: ['Keeps me pale'], variants: ['Causes fear and anxiety'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-cancel', triggers: ['Cancel'], variants: ['Erase / invalidate'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-light-thickens', triggers: ['Light thickens'], variants: ['Darkness is setting in'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-makes-wing', triggers: ['Makes wing'], variants: ['Flies'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-rooky-wood', triggers: ['Rooky wood'], variants: ['Forest inhabited by rooks, or crows'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-droop-drowse', triggers: ['Droop and drowse'], variants: ['Become weak and fall asleep'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-black-agents', triggers: ['Black agents'], variants: ['Evil forces or secret operatives'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-marvellst', triggers: ['Marvell’st'], variants: ['Are astonished'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-hold-thee-still', triggers: ['Hold thee still'], variants: ['Stay quiet / remain calm'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-prithee', triggers: ['Prithee'], variants: ['Please / I ask you'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-bad-begun', triggers: ['Things bad begun make strong themselves by ill'], variants: ['Once a harmful initiative begins, further wrongdoing tends to reinforce it'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-medlar', triggers: ['Medlar'], variants: ['A fruit associated with sexual humor'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-laugh-alone', triggers: ['Laugh alone'], variants: ['Use private sexual humor'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-open-etc', triggers: ['An open et cetera'], variants: ['A sexually suggestive unfinished comparison'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-poperin-pear', triggers: ['Poperin pear'], variants: ['A pear-shaped object used as a sexual joke'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-truckle-bed', triggers: ['Truckle-bed'], variants: ['A low bed that rolls beneath another bed'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-field-bed', triggers: ['Field-bed'], variants: ['A portable or temporary bed'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-to-truckle-bed', triggers: ['I’ll to my truckle-bed'], variants: ['I’m heading to my small bed'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-too-cold-sleep', triggers: ['Too cold for me to sleep'], variants: ['This situation is uncomfortable, so I’m leaving'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-what-light-window', triggers: ['What light through yonder window breaks?'], variants: ['What’s that light appearing through that window?'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-yonder', triggers: ['Yonder'], variants: ['Over there'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-vestal', triggers: ['Vestal'], variants: ['Chaste / sexually pure'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-vestal-livery', triggers: ['Vestal livery'], variants: ['The moon’s pale, chaste appearance'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-none-fools-wear', triggers: ['None but fools do wear it'], variants: ['Only fools would accept that outdated image'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-cast-it-off', triggers: ['Cast it off'], variants: ['Abandon it / rebrand'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-that-she-knew', triggers: ['O, that she knew she were!'], variants: ['If only she realized how much I love her'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-eye-discourses', triggers: ['Her eye discourses'], variants: ['Her expression communicates without words'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-fairest', triggers: ['Fairest'], variants: ['Most beautiful'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-entreat', triggers: ['Entreat'], variants: ['Request / ask'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-what-if', triggers: ['What if'], variants: ['Imagine if'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-shame-those-stars', triggers: ['Shame those stars'], variants: ['Make those stars look inferior'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-doth-lamp', triggers: ['Doth a lamp'], variants: ['Does to an ordinary light'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-airy-region', triggers: ['Airy region'], variants: ['The atmosphere / sky'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-o-that-glove', triggers: ['O, that I were a glove'], variants: ['If only I could become something touching her directly'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-wherefore', triggers: ['Wherefore'], variants: ['Why'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-wherefore-romeo', triggers: ['Wherefore art thou Romeo?'], variants: ['Why do you have to be Romeo—the son of my family’s enemy?'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-art-thou', triggers: ['Art thou'], variants: ['Are you'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-deny-thy-father', triggers: ['Deny thy father'], variants: ['Reject your family affiliation'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-refuse-thy-name', triggers: ['Refuse thy name'], variants: ['Give up the identity and brand attached to your family'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-if-thou-wilt-not', triggers: ['If thou wilt not'], variants: ['If you refuse to do that'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-be-sworn-my-love', triggers: ['Be but sworn my love'], variants: ['Commit yourself exclusively to me'], category: 'lexicalCliche', priority: 40 },
  { id: 'lex-archaic-no-longer-capulet', triggers: ['No longer be a Capulet'], variants: ['I’ll leave my family identity behind'], category: 'lexicalCliche', priority: 40 }
]);

export const phraseRules = Object.freeze([
  { id: 'lex-adjective-stack', triggers: ['small engineering team'], variants: ['cutting-edge, nuanced, scalable, and mission-critical engineering team'], category: 'marketing', priority: 110 },
  { id: 'lex-simple-yet', triggers: ['simple way'], variants: ['simple yet powerful way'], category: 'marketing', priority: 105 },
  { id: 'lex-error', triggers: ['errors', 'error'], variants: ['meaningful correctness gap'], category: 'lexicalCliche', priority: 100 },
  { id: 'lex-task', triggers: ['tasks', 'task'], variants: ['disjoint implementation slice'], category: 'lexicalCliche', priority: 100 },
  { id: 'lex-important', triggers: ['very important', 'important'], variants: ['pivotal', 'load-bearing', 'mission-critical'], category: 'lexicalCliche', priority: 80 },
  { id: 'lex-use', triggers: ['uses', 'using', 'used', 'use'], variants: ['operationalizes', 'leverages', 'harnesses'], category: 'marketing', priority: 70 },
  { id: 'lex-show', triggers: ['demonstrates', 'shows', 'show'], variants: ['underscores', 'showcases', 'illuminates'], category: 'lexicalCliche', priority: 70 },
  { id: 'lex-improve', triggers: ['improvements', 'improvement', 'improves', 'improve'], variants: ['transformative elevation', 'unlocking enhancement', 'meaningful optimization'], category: 'marketing', priority: 70 },
  { id: 'lex-problem', triggers: ['problems', 'problem'], variants: ['evolving friction points', 'multifaceted challenge'], category: 'lexicalCliche', priority: 70 },
  { id: 'lex-complex', triggers: ['complicated', 'complex'], variants: ['deeply nuanced', 'intricately multifaceted'], category: 'lexicalCliche', priority: 60 },
  { id: 'lex-context', triggers: ['contexts', 'context'], variants: ['broader landscape', 'evolving realm'], category: 'lexicalCliche', priority: 60 },
  { id: 'lex-connect', triggers: ['connections', 'connection'], variants: ['connective tissue', 'interplay'], category: 'lexicalCliche', priority: 60 },
  { id: 'lex-system', triggers: ['systems', 'system'], variants: ['platform', 'solution', 'operational ecosystem'], category: 'synonymCycling', priority: 50 },
  { id: 'lex-tool', triggers: ['tools', 'tool'], variants: ['platform', 'solution', 'capability'], category: 'synonymCycling', priority: 50 },
  { id: 'lex-help', triggers: ['helps', 'help'], variants: ['serves to facilitate', 'meaningfully enables'], category: 'marketing', priority: 50 },
  ...archaicPhraseRules,
  ...additionalArchaicPhraseRules
]);

export const tallyDefinitions = Object.freeze([
  ['lexicalCliche', 'Lexical clichés'],
  ['marketing', 'Marketing language'],
  ['hedge', 'Hedges'],
  ['copulaAvoidance', 'Copula avoidance'],
  ['indirectAssociation', 'Indirect association'],
  ['negativeParallelism', 'Negative parallelism'],
  ['ruleOfThree', 'Rule-of-three constructions'],
  ['significance', 'Significance framing'],
  ['awkwardness', 'Controlled awkwardness'],
  ['transition', 'Transition clusters'],
  ['synonymCycling', 'Synonym cycling'],
  ['heading', 'Headings'],
  ['thematicBreak', 'Thematic breaks'],
  ['emDash', 'Em dashes'],
  ['bold', 'Bold spans'],
  ['list', 'Lists'],
  ['emoji', 'Emoji']
]);

export const scoreWeights = Object.freeze({
  lexicalCliche: 1,
  marketing: 2,
  hedge: 2,
  copulaAvoidance: 4,
  indirectAssociation: 4,
  negativeParallelism: 5,
  ruleOfThree: 4,
  significance: 4,
  awkwardness: 3,
  transition: 2,
  synonymCycling: 2,
  heading: 3,
  thematicBreak: 2,
  emDash: 1,
  bold: 1,
  list: 5,
  emoji: 1
});

export function validateRules(rules = phraseRules) {
  const ids = new Set();
  for (const rule of rules) {
    if (!rule.id || ids.has(rule.id)) throw new Error(`Duplicate or empty rule id: ${rule.id}`);
    ids.add(rule.id);
    if (!Array.isArray(rule.triggers) || rule.triggers.length === 0 || rule.triggers.some((item) => !item)) {
      throw new Error(`Rule ${rule.id} needs non-empty triggers`);
    }
    if (!Array.isArray(rule.variants) || rule.variants.length === 0 || rule.variants.some((item) => !item)) {
      throw new Error(`Rule ${rule.id} needs non-empty variants`);
    }
    if (!Number.isFinite(rule.priority) || rule.priority < 0) throw new Error(`Rule ${rule.id} has an invalid priority`);
  }
  return true;
}

validateRules();
